[package]
name = "simrust"
version = "0.1.0"
authors = ["Bjørnar Luteberget <luteberget@gmail.com>"]

[dependencies]
ordered-float="*"
smallvec="*"
regex="*"

[[bin]]
name="main"
path="src/main.rs"
[[bin]]
name="simulator"
path="src/simulator.rs"

[[bin]]
name="parsetest"
path="src/parsetest.rs"
