[package]
name = "rolling"
version = "0.1.0"
authors = ["Bjørnar Luteberget <luteberget@gmail.com>"]

[dependencies]
ordered-float="*"
smallvec="*"
regex="*"
structopt="*"
failure="*"
failure_derive="*"

