[package]
name = "railml2dgraph"
version = "0.1.0"
authors = ["Bjørnar Luteberget <luteberget@gmail.com>"]

[dependencies]
quick-xml = "0.37"
minidom = "0.11"
clap = "2.31"
petgraph="0.6"

[lib]
crate-type=["rlib","staticlib"]

