[package]
name = "vis-rs"
version = "0.1.0"
authors = ["Bjørnar Luteberget <luteberget@gmail.com>"]

[dependencies]
clap = "*"
failure = "*"
failure_derive = "*"
z3 = "*"
rolling = {path = "../rolling" }
serde_json = "*"
svg = "*"
