[package]
name = "rolling"
version = "0.2.0"
authors = ["Bjørnar Luteberget <luteberget@gmail.com>"]

[dependencies]
ordered-float="*"
smallvec="*"
regex="*"
structopt="*"
failure="*"
failure_derive="*"
log = "0.4"


[lib]
crate-type=["rlib","staticlib"]

