[package]
name = "livehtml"
version = "0.1.0"
authors = ["Bjørnar Luteberget <luteberget@gmail.com>"]

[dependencies]
serde_json = "*"
ws = "*"
notify = "*"
#railml2dgraph = {path = "../railml2dgraph"}
#vis-rs = {path = "../vis-rs"}
